import { Component, OnInit } from '@angular/core';
import { AccountService, Account } from '../../services/account.service';
import { TransactionService, Transaction } from '../../services/transaction.service';
import { AiService } from '../../services/ai.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-dashboard',
  template: `
    <div class="dashboard">
      <!-- Stats Row -->
      <div class="stats-grid">
        <mat-card class="stat-card primary-card" *ngFor="let acc of accounts">
          <mat-card-content>
            <div class="stat-label">{{ acc.accountType | titlecase }} Account</div>
            <div class="stat-value">{{ acc.currency }} {{ acc.balance | number:'1.2-2' }}</div>
            <div class="stat-sub">Available: {{ acc.currency }} {{ acc.availableBalance | number:'1.2-2' }}</div>
            <div class="account-number">{{ acc.accountNumber }}</div>
          </mat-card-content>
        </mat-card>

        <mat-card class="stat-card info-card">
          <mat-card-content>
            <div class="stat-label">Total Transactions</div>
            <div class="stat-value">{{ totalTransactions }}</div>
            <div class="stat-sub">Last 30 days</div>
          </mat-card-content>
        </mat-card>
      </div>

      <!-- AI Insights Banner -->
      <mat-card class="insights-card" *ngIf="aiInsights">
        <mat-card-header>
          <mat-icon mat-card-avatar style="color:#7c3aed">smart_toy</mat-icon>
          <mat-card-title>AI Spending Insights</mat-card-title>
          <mat-card-subtitle>Generated by NexaBot</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content>
          <p class="insights-text">{{ aiInsights }}</p>
        </mat-card-content>
      </mat-card>

      <!-- Recent Transactions -->
      <mat-card class="transactions-card">
        <mat-card-header>
          <mat-card-title>Recent Transactions</mat-card-title>
          <span class="spacer"></span>
          <a mat-button routerLink="/transactions">View All</a>
        </mat-card-header>
        <mat-card-content>
          <table mat-table [dataSource]="recentTransactions" class="full-width">
            <ng-container matColumnDef="date">
              <th mat-header-cell *matHeaderCellDef>Date</th>
              <td mat-cell *matCellDef="let tx">{{ tx.createdAt | date:'MMM dd, HH:mm' }}</td>
            </ng-container>
            <ng-container matColumnDef="description">
              <th mat-header-cell *matHeaderCellDef>Description</th>
              <td mat-cell *matCellDef="let tx">{{ tx.description || tx.type }}</td>
            </ng-container>
            <ng-container matColumnDef="amount">
              <th mat-header-cell *matHeaderCellDef>Amount</th>
              <td mat-cell *matCellDef="let tx" [class.credit]="isCreditTx(tx)" [class.debit]="!isCreditTx(tx)">
                {{ isCreditTx(tx) ? '+' : '-' }} {{ tx.currency }} {{ tx.amount | number:'1.2-2' }}
              </td>
            </ng-container>
            <ng-container matColumnDef="status">
              <th mat-header-cell *matHeaderCellDef>Status</th>
              <td mat-cell *matCellDef="let tx">
                <mat-chip [class]="'status-' + tx.status.toLowerCase()">{{ tx.status }}</mat-chip>
              </td>
            </ng-container>
            <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
            <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
          </table>
          <div *ngIf="recentTransactions.length === 0" class="empty-state">
            <mat-icon>receipt_long</mat-icon>
            <p>No transactions yet. Make your first transfer!</p>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .dashboard { display: flex; flex-direction: column; gap: 20px; }
    .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; }
    .stat-card { border-radius: 12px; border: none; }
    .primary-card { background: linear-gradient(135deg, #1a3c5e, #2d6a9f); color: white; }
    .info-card { background: linear-gradient(135deg, #059669, #10b981); color: white; }
    .stat-label { font-size: 12px; opacity: 0.8; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px; }
    .stat-value { font-size: 28px; font-weight: 700; margin-bottom: 4px; }
    .stat-sub { font-size: 12px; opacity: 0.75; }
    .account-number { font-size: 11px; opacity: 0.6; margin-top: 8px; font-family: monospace; }
    .insights-card { border-left: 4px solid #7c3aed; }
    .insights-text { color: #374151; line-height: 1.7; white-space: pre-line; }
    .transactions-card mat-card-header { display: flex; align-items: center; margin-bottom: 12px; }
    .spacer { flex: 1; }
    .full-width { width: 100%; }
    .credit { color: #059669; font-weight: 600; }
    .debit { color: #dc2626; font-weight: 600; }
    .status-completed { background: #d1fae5 !important; color: #065f46 !important; }
    .status-flagged { background: #fee2e2 !important; color: #991b1b !important; }
    .status-pending { background: #fef3c7 !important; color: #92400e !important; }
    .empty-state { text-align: center; padding: 40px; color: #9ca3af; }
    .empty-state mat-icon { font-size: 48px; height: 48px; width: 48px; }
  `]
})
export class DashboardComponent implements OnInit {
  accounts: Account[] = [];
  recentTransactions: Transaction[] = [];
  aiInsights = '';
  totalTransactions = 0;
  displayedColumns = ['date', 'description', 'amount', 'status'];

  constructor(
    private accountService: AccountService,
    private transactionService: TransactionService,
    private aiService: AiService,
    private authService: AuthService
  ) {}

  ngOnInit() {
    const user = this.authService.getCurrentUser();
    if (!user) return;

    this.accountService.getMyAccounts(user.username).subscribe(accounts => {
      this.accounts = accounts;
      if (accounts.length > 0) {
        this.transactionService.getHistory(accounts[0].accountNumber, 0, 5).subscribe(page => {
          this.recentTransactions = page.content;
          this.totalTransactions = page.totalElements;
          this.loadAiInsights();
        });
      }
    });
  }

  loadAiInsights() {
    const summary = `User has ${this.accounts.length} account(s). Recent ${this.recentTransactions.length} transactions loaded.`;
    this.aiService.getInsights(summary).subscribe({
      next: (res) => this.aiInsights = res.insights,
      error: () => this.aiInsights = ''
    });
  }

  isCreditTx(tx: Transaction): boolean {
    const user = this.authService.getCurrentUser();
    return tx.type === 'DEPOSIT' || (this.accounts.some(a => a.accountNumber === tx.toAccountNumber));
  }
}
